spring:
  datasource:
    url: jdbc:mysql://namox.idi.ntnu.no:3306/tinit
  docker:
    compose:
      file: compose.prod.yaml
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /api-docs